language: node_js
  - "8"

branches:
  only:
  - master

before_script:
  - npm install -g ganache-cli
  - npm install -g truffle@5.0.0

script:
  - ./node_modules/.bin/eslint test/**/*.js
  - ganache-cli &
  - sleep 5
  - truffle test
