language: node_js
  - "8"

branches:
  only:
  - master

before_script:
  - npm install -g ganache-cli
  - npm install -g truffle@5.0.0
  - npm install

script:
  - ./node_modules/.bin/eslint test/**/*.js
  - ganache-cli &
  - sleep 5
  - truffle test

# deploy:
#   provider: script
#   skip_cleanup: true
#   script: truffle migrate -f 3 --network rinkeby
#   on:
#     branch: master